export default [
  {
    itemId: "ITEM00000000000000000020",
    itemType: "Accessory",
    price: 3500,
    status: "available",
    brand: "Lavemi",
    itemName: "Lavemi Men's Real Leather Ratchet Dress Casual Belt",
    quantity: 3,
    material: "Leather",
    color: "Black",
    accessoryType: "belt",
    image: [
      'black_belt_1.jpeg',
      'black_belt_2.jpeg',
      'black_belt_3.jpeg',
      'black_belt_4.jpeg',
    ],
    id: 1,
    buckleType: "Ratchet",
    size: 40,
  },
  {
    itemId: "ITEM00000000000000000021",
    itemType: "Accessory",
    price: 3800,
    status: "available",
    brand: "beltox fine",
    itemName: "beltox fine Men’s Casual Leather Jeans Belt",
    quantity: 3,
    material: "Genuine Leather",
    color: "Black",
    accessoryType: "belt",
    image: [
      'beltox_belt_1.jpg',
      'beltox_belt_2.jpg',
      'beltox_belt_3.jpg',
      'beltox_belt_4.jpg',
    ],
    id: 2,
    buckleType: "Thick Alloy Prong Buckle",
    size: 30,
  },
  {
    itemId: "ITEM00000000000000000022",
    itemType: "Accessory",
    price: 4000,
    status: "available",
    brand: "Timberland PRO",
    itemName: "Timberland PRO Men's 38mm Boot Leather Belt",
    quantity: 2,
    material: "100% Leather",
    color: "Brown",
    accessoryType: "belt",
    image: [
      'timberland_belt_1.jpg',
      'timberland_belt_2.jpg',
      'timberland_belt_3.jpg',
      'timberland_belt_4.jpg',
      'timberland_belt_5.jpg',
    ],
    id: 3,
    buckleType: "Timberland Logo Buckle",
    size: 38,
  },
];
