export default [
  {
    itemId: "ITEM00000000000000000019",
    itemType: "preDesigned",
    price: 10000,
    status: "available",
    name: "Men's Casual Slim Fit Suit Blazer Jacket One Button Lightweight Sport Coats Formal Dress Daily Business Suit Jacket",
    costumeType: "jacket",
    size: { L: 3, M: 1, S: 3 },
    color: "Black",
    images: [
      "two_piece_slim_fit_casual_one_button_solid_suit_1.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_2.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_3.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_4.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_5.jpg",
    ],
  },
  {
    itemId: "ITEM00000000000000000020",
    itemType: "preDesigned",
    price: 12000,
    status: "available",
    name: "MAGE MALE Men's Slim Fit Suit Separates,Single Breasted Solid Jacket Vest Pants",
    costumeType: "jacket",
    size: { L: 1, M: 1, S: 2 },
    color: "Black",
    images: [
      "mage_male_men_slim_fit_suit_1.jpg",
      "mage_male_men_slim_fit_suit_2.jpg",
      "mage_male_men_slim_fit_suit_3.jpg",
      "mage_male_men_slim_fit_suit_4.jpg",
    ],
  },
  {
    itemId: "ITEM00000000000000000021",
    itemType: "preDesigned",
    price: 15000,
    status: "available",
    name: "COOFANDY Men's Floral Suit Jacket Embroidered Wedding Blazer Party Dinner Tuxedo",
    costumeType: "jacket",
    size: { L: 1, M: 1, S: 2 },
    color: "Black",
    images: [
      "floral_suit_jacket_embroidered_wedding_blazer_1.jpg",
      "floral_suit_jacket_embroidered_wedding_blazer_2.jpg",
      "floral_suit_jacket_embroidered_wedding_blazer_3.jpg",
      "floral_suit_jacket_embroidered_wedding_blazer_4.jpg",
    ],
  },
  {
    itemId: "ITEM00000000000000000022",
    itemType: "preDesigned",
    price: 18600,
    status: "available",
    name: "COOFANDY Men's 3 Piece Slim Fit Suit Set One Button Jacket Blazer Vest Pants Set Wedding Formal Prom Tuxedo Suits",
    costumeType: "jacket & pant",
    size: { L: 1, M: 1, S: 0 },
    color: "Black",
    images: [
      "two_piece_slim_fit_casual_one_button_solid_suit_1.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_2.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_3.jpg",
      "two_piece_slim_fit_casual_one_button_solid_suit_4.jpg",
    ],
  },
  {
    itemId: "ITEM00000000000000000023",
    itemType: "preDesigned",
    price: 20000,
    status: "available",
    name: "Mens Suits 2 Piece Slim Fit Casual One Button Solid Suits for Mens Business Wedding Party Jacket Blazer & Pants Set",
    costumeType: "jacket & pant",
    size: { L: 1, M: 0, S: 2 },
    color: "Black",
    images: [
      "three_piece_suits_one_button_blazer_jacket_2.jpg",
      "three_piece_suits_one_button_blazer_jacket_3.jpg",
      "three_piece_suits_one_button_blazer_jacket_4.jpg",
      "three_piece_suits_one_button_blazer_jacket_1.jpg",
    ],
  },
];
