export default [
  {
    itemId: "ITEM00000000000000000014",
    itemType: "Accessory",
    price: 3500,
    status: "available",
    brand: "Bata",
    itemName: "Black leather shoes",
    quantity: 1,
    material: "Leather",
    color: "Black",
    accessoryType: "shoe",
    image: [
      'black_leather_shoe_1.jpeg',
      'black_leather_shoe_2.jpeg',
      'black_leather_shoe_3.jpeg',
      'black_leather_shoe_4.jpeg',
    ],
    id: 1,
    style: "Boat",
    size: 10,
  },
  {
    itemId: "ITEM00000000000000000015",
    itemType: "Accessory",
    price: 4000,
    status: "available",
    brand: "DSI",
    itemName: "Brown Leather Formal Shoes",
    quantity: 2,
    material: "Leather",
    color: "Brown",
    accessoryType: "shoe",
    image: [
      'brown_leather_shoe_1.jpeg',
      'brown_leather_shoe_2.jpeg',
      'brown_leather_shoe_3.jpeg',
      'brown_leather_shoe_4.jpeg',
    ],
    id: 2,
    style: "Loafer",
    size: 8,
  },
  {
    itemId: "ITEM00000000000000000016",
    itemType: "Accessory",
    price: 5200,
    status: "available",
    brand: "DSI",
    itemName: "Maroon Style Leather Shoes",
    quantity: 2,
    material: "Leather",
    color: "Maroon",
    accessoryType: "shoe",
    image: [
      'maroon_design_1.jpeg',
      'maroon_design_2.jpeg',
      'maroon_design_3.jpeg',
      'maroon_design_4.jpeg',
    ],
    id: 3,
    style: "Desert",
    size: 12,
  },
];
