export default [
  {
    itemId: "ITEM00000000000000000017",
    itemType: "Accessory",
    price: 3500,
    status: "available",
    brand: "DAZI",
    itemName: "Men's Skinny Tie",
    quantity: 2,
    material: "Cotton",
    color: "Black",
    accessoryType: "tie",
    image: [
      'solid_pure_black_men_tie_1.jpg',
      'solid_pure_black_men_tie_2.jpg',
      'solid_pure_black_men_tie_3.jpg',
      'solid_pure_black_men_tie_4.jpg',
      'solid_pure_black_men_tie_5.jpg',
    ],
    id: 1,
    pattern: "Solid",
    width: 3.1,
  },
  {
    itemId: "ITEM00000000000000000018",
    itemType: "Accessory",
    price: 4000,
    status: "available",
    brand: "Ambesonne",
    itemName: "Ambesonne Multi Color Tie",
    quantity: 2,
    material: "Silk",
    color: "Multicolor",
    accessoryType: "tie",
    image: [
      'gingham_check_stripe_tie_1.jpg',
      'gingham_check_stripe_tie_2.jpg',
      'gingham_check_stripe_tie_3.jpg',
      'gingham_check_stripe_tie_4.jpg',
      'gingham_check_stripe_tie_5.jpg',
      'gingham_check_stripe_tie_6.jpg',
      'gingham_check_stripe_tie_7.jpg',
    ],
    id: 2,
    pattern: "Colored Animal",
    width: 3.7,
  },
  {
    itemId: "ITEM00000000000000000019",
    itemType: "Accessory",
    price: 5200,
    status: "available",
    brand: "Brooks Brothers",
    itemName: "Brooks Brothers Stripe Tie",
    quantity: 3,
    material: "Silk",
    color: "Maroon",
    accessoryType: "tie",
    image: [
      'maroon_stripe_men_tie_1.jpg',
      'maroon_stripe_men_tie_2.jpg',
      'maroon_stripe_men_tie_3.jpg',
      'maroon_stripe_men_tie_4.jpg',
      'maroon_stripe_men_tie_5.jpg',
    ],
    id: 3,
    pattern: "Striped",
    width: 3.15,
  },
];
